export const d = {
  btn: {
    primary: 'btn-primary',
    secondary: 'btn-secondary',
    danger: 'btn-danger',
    primaryMt2: 'btn-primary mt-2',
    dangerMt2: 'btn-danger mt-2',
    secondaryXs: 'btn-secondary px-2 py-1 text-xs',
    dangerXs: 'btn-danger px-2 py-1 text-xs',
    emerald: 'btn-primary bg-emerald-600 hover:bg-emerald-700',
    emeraldSm: 'h-9 rounded-md bg-emerald-600 px-4 text-sm font-bold text-white hover:bg-emerald-700 disabled:opacity-60',
    redSm: 'h-9 rounded-md bg-red-600 px-4 text-sm font-bold text-white hover:bg-red-700 disabled:opacity-60',
    accept: 'rounded bg-emerald-600 px-3 py-2 font-semibold text-white',
    decline: 'rounded bg-rose-600 px-3 py-2 font-semibold text-white',
    inProgress: 'rounded bg-sky-600 px-3 py-2 font-semibold text-white',
    resolved: 'rounded bg-violet-600 px-3 py-2 font-semibold text-white',
    acceptDisabled: 'rounded bg-emerald-600 px-3 py-2 font-semibold text-white disabled:opacity-60',
    declineDisabled: 'rounded bg-rose-600 px-3 py-2 font-semibold text-white disabled:opacity-60',
    inProgressDisabled: 'rounded bg-sky-600 px-3 py-2 font-semibold text-white disabled:opacity-60',
    resolvedDisabled: 'rounded bg-violet-600 px-3 py-2 font-semibold text-white disabled:opacity-60',
    neutral: 'btn-secondary',
    warning: 'rounded bg-[#1f4e79] px-4 py-2 font-semibold text-white hover:bg-[#173a5b] disabled:opacity-60',
  },

  modal: {
    overlay: 'fixed inset-0 z-40 flex items-center justify-center bg-slate-900/70 p-4',
    card: 'w-full max-w-2xl rounded-lg bg-white p-3 shadow-xl',
    header: 'mb-2 flex items-center justify-between',
    title: 'text-sm font-bold text-slate-700',
    close: 'rounded border border-slate-300 px-2 py-1 text-xs font-semibold text-slate-600',
    image: 'max-h-[82dvh] w-full rounded border border-slate-200 object-contain',
  },

  shell: {
    root: 'admin-desktop-scale app-bg min-h-[var(--admin-viewport-height)] w-full overflow-x-hidden text-slate-900',
    layout: 'flex min-h-[var(--admin-viewport-height)] flex-col min-[820px]:grid min-[820px]:grid-cols-[228px_minmax(0,1fr)] xl:grid-cols-[240px_minmax(0,1fr)]',
    aside: 'hidden flex-col gap-4 border-r border-slate-700/60 bg-[#0b2e4e] px-4 py-4 min-[820px]:flex min-[820px]:min-h-[var(--admin-viewport-height)]',
    mobileTop: 'sticky top-0 z-30 border-b border-slate-300 bg-white/95 px-3 py-2 pt-[max(0.5rem,env(safe-area-inset-top))] backdrop-blur min-[820px]:hidden',
    mobileTopInner: 'flex items-center justify-between gap-3',
    mobileLogoWrap: 'flex items-center gap-2',
    mobileLogo: 'h-9 w-9 rounded-full border border-[#f4b400] bg-white object-cover',
    mobileBrand: 'text-lg font-extrabold leading-none text-[#0b2e4e]',
    mobileLogout: 'rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-sm font-semibold text-slate-700',
    mobileNav: 'fixed bottom-0 left-0 right-0 z-40 grid grid-cols-6 gap-1 border-t border-slate-300 bg-white/95 p-2 pb-[calc(env(safe-area-inset-bottom)+0.5rem)] backdrop-blur min-[820px]:hidden',
    mobileNavItem: 'flex min-h-11 min-w-0 items-center justify-center rounded-lg px-1 py-2 text-center font-bold transition-colors',
    mobileNavActive: 'bg-[#1f4e79] text-white',
    mobileNavIdle: 'text-[#1f4e79] hover:bg-slate-100',
    logoWrap: 'flex items-center gap-2 rounded-2xl border border-slate-500/30 bg-[#163b60] px-3 py-2.5',
    logo: 'h-9 w-9 rounded-full border border-[#f4b400] bg-white object-cover',
    city: 'text-[0.74rem] uppercase tracking-[0.2em] text-slate-300',
    brand: 'text-[1.95rem] font-extrabold leading-none text-white lg:text-[2.08rem]',
    nav: 'flex flex-col gap-3',
    navItem: 'flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-base font-semibold tracking-[0.01em] transition-colors min-[820px]:py-3.5 min-[820px]:text-[1.08rem]',
    navIcon: 'h-5 w-5 shrink-0',
    navItemActive: 'bg-[#2a5d8d] text-white shadow-sm',
    navItemIdle: 'text-slate-100 hover:bg-[#163b60]',
    monitoringDropdownWrap: 'mb-2 mt-3 space-y-3',
    monitoringDropdownPanel: 'space-y-2 rounded-xl border border-slate-500/35 bg-[#163b60] p-2',
    monitoringDropdownButton: 'w-full rounded-lg bg-[#2a5d8d] px-3 py-2 text-left text-sm font-bold text-white transition hover:bg-[#346e9f]',
    monitoringDropdownButtonActive: 'mt-2 w-full rounded-lg border border-sky-300 bg-sky-700 px-3 py-2 text-left text-sm font-bold text-white',
    monitoringDropdownRows: 'mt-2 max-h-[34vh] space-y-2 overflow-y-auto pr-1',
    monitoringDropdownItem: 'flex w-full items-center justify-between rounded-xxl bg-[#2a5d8d] px-3 py-3 text-left text-base font-semibold text-white shadow-sm',
    monitoringDropdownCheck: 'h-4 w-4 min-h-4 min-w-4 max-h-4 max-w-4 shrink-0 rounded-sm border border-slate-200 accent-sky-400',
    monitoringFloodLegendDetails: 'rounded-lg border border-slate-500/45 bg-[#0f2f4d] p-2 text-xs text-slate-100',
    monitoringFloodLegendSummary: 'cursor-pointer font-bold text-sky-100',
    monitoringFloodLegendBody: 'mt-2 max-h-28 space-y-1 overflow-y-auto pr-1 text-[11px] leading-relaxed text-slate-200',
    monitoringFloodLegendRow: 'flex items-center gap-2',
    monitoringFloodLegendSwatch: 'inline-block h-2.5 w-4 rounded-sm border border-slate-100/60',
    logout: 'mt-1 w-full rounded-xl border border-slate-500/40 bg-[#133858] px-3 py-3 text-base font-bold text-white transition hover:bg-[#1b476f] lg:mt-auto',
    mainBase: 'w-full min-w-0 px-3 py-3 pb-24 md:px-4 md:py-4 min-[820px]:pb-4 xl:px-5',
    mainNoScroll: 'min-[820px]:h-[var(--admin-viewport-height)] min-[820px]:overflow-hidden',
    mainScroll: 'min-[820px]:max-h-[var(--admin-viewport-height)] min-[820px]:overflow-y-auto',
    header: 'mb-2.5 rounded-2xl border border-slate-200 bg-white/90 px-4 py-3 shadow-sm backdrop-blur',
    headerInner: 'flex flex-wrap items-center justify-between gap-3',
    h1: 'text-xl font-extrabold leading-tight text-[#0b2e4e] md:text-[1.7rem]',
    subtitle: 'mt-1 text-[0.95rem] text-slate-600',
    actions: 'flex flex-wrap gap-2',
    accountActions: 'grid w-full grid-cols-1 gap-3 sm:w-auto sm:grid-cols-[13rem_15rem] sm:justify-end',
    accountActionSlot: 'flex h-12 min-w-0 items-center justify-end',
    accountTypeControl: 'relative h-12 w-full',
    accountTypeSelect: 'h-12 w-full appearance-none rounded-xl border-2 border-[#1f4e79] bg-[#1f4e79] py-2 pl-4 pr-11 text-base font-bold text-white shadow-sm outline-none transition hover:bg-[#173a5b] focus:ring-4 focus:ring-sky-200 [&>option]:bg-white [&>option]:text-slate-900',
    accountTypeArrow: 'pointer-events-none absolute right-4 top-1/2 h-5 w-5 -translate-y-1/2 text-white',
  },

  page: {
    panelFill: 'panel flex h-full flex-col p-2',
    panelFillMd: 'panel flex h-full flex-col p-3',
    stack: 'space-y-3',
    error: 'rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700',
    loading: 'text-sm text-slate-500',
    sectionGrid: 'grid gap-2',
  },

  card: {
    metric: 'metric-card bg-white text-sm',
    metricValue: 'text-2xl font-extrabold',
    metricLabel: 'font-semibold text-slate-600',
  },

  form: {
    input: 'h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm',
    inputSm: 'h-9 rounded border border-slate-300 px-2 text-sm',
    inputSmDisabled: 'h-9 rounded border border-slate-200 bg-slate-100 px-2 text-sm text-slate-600',
    selectSm: 'w-full rounded border border-slate-300 px-2 py-1',
    textareaSm: 'w-full rounded border border-slate-300 px-2 py-1',
    textarea: 'mt-2 h-16 w-full rounded-lg border border-slate-300 bg-white p-2 text-sm',
    select: 'h-10 rounded-lg border border-slate-300 px-2 text-sm',
  },

  table: {
    main: 'data-table',
    wrap: 'active-list-scroll flex-1 overflow-auto rounded-md border border-slate-300 bg-white',
    empty: 'px-2 py-8 text-center text-sm text-slate-500',
  },

  login: {
    root: 'admin-desktop-scale app-bg min-h-[var(--admin-viewport-height)] w-full',
    layout: 'grid min-h-[var(--admin-viewport-height)] w-full bg-white lg:grid-cols-[1.02fr_0.98fr]',
    left: 'order-2 flex flex-col justify-center bg-[linear-gradient(155deg,#f8fbff_0%,#edf3fb_60%,#e4edf8_100%)] px-5 py-8 sm:px-10 md:px-14 lg:order-1 lg:px-16',
    overline: 'mb-5 text-xs font-semibold uppercase tracking-[0.28em] text-slate-500 sm:mb-7',
    title: "mb-2 text-[clamp(2rem,5vw,3rem)] font-black tracking-tight text-[#0b2e4e] [font-family:'Sora',sans-serif]",
    subtitle: 'mb-6 max-w-xl text-sm text-slate-600 sm:mb-8',
    form: 'w-full max-w-[min(560px,100%)] space-y-4 sm:space-y-5',
    input: 'h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-sm text-slate-700 shadow-[0_2px_6px_rgba(15,41,72,0.12)] outline-none transition focus:border-[#1f4e79]',
    rememberLabel: 'flex cursor-pointer items-center gap-2 text-sm font-medium text-[#1f3c54]',
    checkbox: 'h-4 w-4 rounded border-slate-400 text-[#12314b]',
    error: 'text-sm font-medium text-red-600',
    loginBtn: 'h-12 w-full rounded-xl bg-[#1f4e79] text-base font-bold text-white shadow-[0_4px_10px_rgba(18,49,75,0.25)] transition hover:bg-[#173a5b] disabled:cursor-not-allowed disabled:opacity-60',
    right: 'relative order-1 flex min-h-[220px] items-center justify-center overflow-hidden bg-[#0f3558] sm:min-h-[280px] lg:order-2 lg:min-h-[var(--admin-viewport-height)]',
    heroImg: 'absolute inset-0 h-full w-full object-cover opacity-20',
    overlay: 'absolute inset-0 bg-gradient-to-b from-[#1f5f93]/45 to-[#0b2740]/75',
    heroBody: 'relative z-10 flex max-w-sm flex-col items-center px-4 text-center text-white',
    seal: 'mb-4 h-24 w-24 rounded-full border-[5px] border-[#f6d84c] bg-white object-cover shadow-xl sm:h-28 sm:w-28 lg:mb-5 lg:h-36 lg:w-36 lg:border-[6px]',
    heroTitle: "text-[clamp(1rem,3.8vw,2rem)] font-black leading-tight [font-family:'Sora',sans-serif]",
  },

  dashboard: {
    root: 'relative flex min-h-0 flex-col gap-2 min-[820px]:h-[calc(var(--admin-viewport-height)-8.5rem)] min-[820px]:overflow-hidden',
    topActions: 'btn-secondary',
    topPrimary: 'btn-primary',
    metricsGrid: 'grid shrink-0 gap-2 sm:grid-cols-2 xl:grid-cols-4',
    metricGradient: 'metric-card cursor-default border-0 bg-gradient-to-r py-2 text-white shadow-md transition duration-300 ease-out hover:-translate-y-1 hover:scale-[1.02] hover:brightness-110 hover:shadow-xl',
    cardEmergency: 'from-[#f25358] to-[#ef8b8f]',
    cardTeams: 'from-[#2ca3d8] to-[#67c8db]',
    cardEvac: 'from-[#efad09] to-[#efd24c]',
    cardEvacuees: 'from-[#2bb39e] to-[#72d5a2]',
    metricValue: 'text-[1.55rem] font-black leading-none',
    metricLabel: 'mt-1 text-[0.95rem] font-extrabold',
    overviewGrid: 'grid min-h-[24rem] gap-2 min-[820px]:min-h-0 min-[820px]:flex-[1.05] min-[820px]:grid-cols-[minmax(0,1.7fr)_minmax(175px,0.58fr)_minmax(230px,0.82fr)] 2xl:grid-cols-[minmax(0,1.85fr)_minmax(230px,0.58fr)_minmax(300px,0.78fr)]',
    reportsPanel: 'flex h-[20rem] min-h-0 min-w-0 flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm min-[820px]:h-full',
    reportsTitle: 'font-black text-[#173750]',
    reportsContentGrid: 'min-h-0 flex-1 overflow-auto',
    reportsWrap: 'mt-2 min-h-0 flex-1 overflow-auto',
    insightsRow: 'grid min-h-[20rem] gap-2 min-[820px]:min-h-0 min-[820px]:flex-[0.95] min-[820px]:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]',
    reportsTable: 'w-full table-fixed text-left text-sm [&_thead]:sticky [&_thead]:top-0 [&_thead]:z-10 [&_thead]:bg-slate-50 [&_th]:px-2.5 [&_th]:py-3 [&_th]:text-[0.7rem] [&_th]:uppercase [&_th]:tracking-wide [&_th]:text-slate-600 [&_th:nth-child(1)]:w-[18%] [&_th:nth-child(2)]:w-[27%] [&_th:nth-child(3)]:w-[22%] [&_th:nth-child(4)]:w-[19%] [&_th:nth-child(5)]:w-[14%] [&_td]:overflow-hidden [&_td]:text-ellipsis [&_td]:whitespace-nowrap [&_td]:px-2.5 [&_td]:py-3 [&_tbody_tr]:border-t [&_tbody_tr]:border-slate-100 [&_tbody_tr:hover]:bg-slate-50',
    thHiddenMd: 'hidden md:table-cell',
    tdStrong: 'font-semibold text-slate-800',
    tdTruncate: 'truncate',
    statusChip: 'status-chip bg-slate-200 text-slate-700',
    muted: 'text-slate-400',
    statusMapPanel: 'contents',
    statusColumn: 'flex h-[20rem] min-h-0 min-w-0 flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm min-[820px]:h-full',
    statusCard: 'flex min-h-0 flex-1 flex-col',
    statusTitle: 'shrink-0 border-b border-slate-200 px-3 py-2 text-[1rem] font-black leading-tight text-[#173750]',
    statusList: 'min-h-0 flex-1 space-y-2 overflow-y-auto overscroll-contain p-3',
    areaCardBase: 'rounded-lg border p-2',
    areaCardActive: 'border-emerald-300 bg-emerald-50/50',
    areaCardIdle: 'border-slate-200 bg-slate-50',
    areaName: 'text-sm font-extrabold text-[#12314b]',
    areaBarangay: 'text-xs text-slate-500',
    areaMeta: 'mt-1 flex items-center justify-between text-xs',
    areaOcc: 'font-semibold text-amber-600',
    areaCap: 'text-slate-600',
    mapWrap: 'relative flex h-[20rem] min-h-0 flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm min-[820px]:h-full',
    mapFrame: 'min-h-0 w-full flex-1 border-0',
    rainRankCard: 'flex min-h-0 flex-col overflow-hidden rounded-xl border border-sky-200 bg-sky-50 p-3 shadow-sm',
    rainRankPopover: 'absolute left-0 right-0 top-[calc(100%+0.5rem)] z-50 max-h-[50dvh] overflow-auto rounded-xl border border-sky-200 bg-sky-50 p-3 shadow-2xl',
    rainRankHead: 'flex items-start justify-between gap-2 border-b border-sky-200 pb-2',
    rainRankTitle: 'text-sm font-black text-sky-900',
    rainRankUpdated: 'text-xs text-slate-500',
    rainRankEmpty: 'pt-2 text-sm text-slate-600',
    rainRankList: 'mt-2 grid gap-2 sm:grid-cols-2',
    rainRankRow: 'rounded-md border border-sky-200 bg-white p-2',
    rainRankName: 'text-xs font-extrabold text-[#12314b]',
    rainRankMeta: 'text-xs font-semibold text-slate-700',
    waterLevels: 'flex min-h-0 flex-col overflow-hidden rounded-xl border border-cyan-200 bg-cyan-50/70 p-3 shadow-sm',
    waterLevelsHead: 'flex items-center justify-between gap-2',
    waterLevelsTitle: 'text-sm font-black text-[#143650]',
    waterLevelsLink: 'text-xs font-bold text-sky-700 hover:text-sky-900',
    waterLevelsLabels: 'mt-2 grid grid-cols-[minmax(6rem,1fr)_4.5rem_3rem_4.25rem_3.5rem_4rem] gap-1 border-b border-cyan-200 px-2 pb-1 text-center text-[0.6rem] font-extrabold uppercase tracking-wide text-slate-500 [&>span:first-child]:text-left',
    waterLevelsList: 'grid min-h-0 flex-1 auto-rows-fr overflow-hidden',
    waterLevelsRow: 'grid h-full grid-cols-[minmax(6rem,1fr)_4.5rem_3rem_4.25rem_3.5rem_4rem] items-center gap-1 whitespace-nowrap border-b border-white/60 px-2 py-1.5 text-center text-xs tabular-nums text-slate-800 transition-colors last:border-b-0',
    waterLevelsBarangay: 'text-left font-bold text-[#143650]',
    waterLevelsStatus: 'justify-self-center rounded-full border px-2 py-0.5 text-[0.65rem] font-extrabold',
    waterLevelsStatusActive: 'border-emerald-300 bg-emerald-100 text-emerald-800',
    waterLevelsStatusUnavailable: 'border-slate-300 bg-slate-200 text-slate-600',
    waterLevelsEmpty: 'py-3 text-xs text-slate-500',
    postUpdateFab: 'group fixed bottom-20 right-4 z-[5000] flex h-16 w-16 items-center justify-start overflow-hidden rounded-full bg-[#1f4e79] text-white shadow-[0_8px_24px_rgba(15,23,42,0.35)] transition-[width,background-color,box-shadow] duration-300 hover:w-44 hover:bg-[#173a5b] hover:shadow-[0_12px_30px_rgba(15,23,42,0.45)] focus:w-44 focus:bg-[#173a5b] focus:outline-none focus:ring-4 focus:ring-sky-300/50 sm:bottom-6 sm:right-6',
    postUpdateFabIcon: 'flex h-16 w-16 shrink-0 items-center justify-center text-4xl font-light leading-none transition-transform duration-300 group-hover:rotate-90 group-focus:rotate-90',
    postUpdateFabLabel: 'whitespace-nowrap pr-6 text-base font-extrabold opacity-0 transition-opacity delay-75 duration-200 group-hover:opacity-100 group-focus:opacity-100',
    composeGrid: 'grid gap-2 xl:grid-cols-2',
    composePanel: 'panel p-3',
    composeTitle: 'text-[1rem] font-black',
    selectGrid: 'mt-2 grid grid-cols-2 gap-2',
  },

  admin: {
    actionAdd: 'btn-primary',
    root: 'flex h-[calc(100dvh-8.7rem)] min-h-0 flex-col rounded-xl bg-[#eaf3fb] p-3 sm:p-4 lg:h-[calc(var(--admin-viewport-height)-9.2rem)]',
    headerRow: 'mb-3 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm',
    title: 'text-lg font-black text-[#1a3650] sm:text-xl',
    searchRow: 'flex flex-wrap items-center gap-2',
    search: 'h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm sm:w-80',
    archiveButton: 'inline-flex h-10 items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 text-sm font-semibold text-[#1a3650] hover:bg-slate-50',
    archiveIcon: 'h-4 w-4 object-contain',
    form: 'mb-3 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-2 xl:grid-cols-4',
    idBox: 'rounded border border-slate-300 bg-white px-2 py-2 text-sm font-semibold text-slate-700',
    formActions: 'flex flex-wrap gap-2 sm:col-span-2 xl:col-span-4',
    tableHead: 'sticky top-0',
    thHiddenMd: 'hidden md:table-cell',
    thHiddenLg: 'hidden lg:table-cell',
    thHiddenXl: 'hidden xl:table-cell',
    row: 'text-[#2b465b]',
    truncate: 'truncate',
    tdHiddenTruncateMd: 'hidden truncate md:table-cell',
    tdHiddenLg: 'hidden lg:table-cell',
    tdHiddenTruncateXl: 'hidden truncate xl:table-cell',
    actions: 'flex gap-1',
    archiveModalCard: 'w-full max-w-3xl rounded-lg bg-white p-3 shadow-xl',
    archiveModalBody: 'max-h-[75dvh] overflow-auto pr-1',
    archiveList: 'space-y-2',
    archiveItem: 'flex flex-wrap items-start justify-between gap-2 rounded-lg border border-slate-200 bg-slate-50 p-2',
    archiveName: 'text-sm font-bold text-[#1a3650]',
    archiveMeta: 'text-xs text-slate-600',
    archiveActions: 'flex w-full flex-col gap-2 sm:w-auto sm:flex-row sm:justify-end',
    archiveActionButton: 'w-full sm:w-auto whitespace-nowrap',
    archiveEmpty: 'text-sm text-slate-500',
  },

  evac: {
    actionAdd: 'btn-primary bg-emerald-600 hover:bg-emerald-700',
    root: 'flex h-[calc(100dvh-8.7rem)] min-h-0 flex-col rounded-xl bg-[#eaf3fb] p-3 sm:p-4 lg:h-[calc(var(--admin-viewport-height)-9.2rem)]',
    grid: 'grid min-h-0 flex-1 gap-3 xl:grid-cols-[1.3fr_1fr] xl:overflow-hidden',
    mapSection: 'flex min-h-[24rem] flex-col rounded-xl border border-slate-200 bg-white p-4 shadow-sm xl:min-h-0',
    mapTitle: 'text-lg font-black leading-tight text-[#173750]',
    mapWrap: 'mt-3 min-h-0 flex-1 overflow-hidden rounded-lg border border-slate-200 bg-white',
    mapFrame: 'h-full w-full border-0',
    detailSection: 'flex min-h-[24rem] flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm xl:min-h-0',
    detailTitle: 'border-b border-slate-200 px-4 py-3 text-lg font-black text-[#173750]',
    detailBody: 'px-4 py-3',
    detailLabel: 'mb-2 text-xs font-bold text-slate-600',
    formStack: 'space-y-1.5',
    twoCol: 'grid gap-2 sm:grid-cols-2',
    threeCol: 'grid gap-2 sm:grid-cols-3',
    formActions: 'mt-2 grid gap-2 sm:grid-cols-[1fr_auto]',
    formActionsWide: 'mt-2 grid gap-2 sm:grid-cols-3',
    editOnlyActions: 'mt-3 flex w-full justify-end',
    otherWrap: 'min-h-0 flex-1 border-t border-slate-200 px-4 py-3',
    otherTitle: 'mb-2 text-[0.95rem] font-black',
    otherList: 'h-full min-h-0 space-y-2 overflow-y-auto pr-1',
    otherItem: 'w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-left transition hover:border-sky-300 hover:bg-sky-50',
    otherName: 'text-sm font-black text-[#12314b]',
    otherBarangay: 'text-xs text-slate-500',
    otherDistance: 'text-sm font-bold text-teal-600',
  },

  monitoring: {
    actionEvac: 'btn-secondary',
    floodHeaderAction: 'btn-primary',
    sensorManagerOverlay: 'fixed inset-0 z-[6000] flex items-center justify-center bg-slate-950/65 p-4 backdrop-blur-sm',
    sensorManagerCard: 'w-full max-w-3xl overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl',
    sensorManagerHead: 'flex items-center justify-between gap-3 border-b border-slate-200 px-5 py-4',
    sensorManagerTitle: 'text-xl font-black text-[#19374f]',
    sensorManagerClose: 'rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-bold text-slate-600 hover:bg-slate-100',
    sensorManagerBody: 'max-h-[65dvh] overflow-y-auto p-4',
    sensorManagerError: 'mb-3 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm font-semibold text-red-700',
    sensorList: 'space-y-2',
    sensorRow: 'grid items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3 sm:grid-cols-[minmax(0,1fr)_auto_auto_auto]',
    sensorBarangay: 'font-extrabold text-[#19374f]',
    sensorHardware: 'text-sm font-bold text-slate-600',
    sensorActiveButton: 'rounded-lg bg-emerald-600 px-3 py-2 text-sm font-extrabold text-white transition hover:bg-emerald-700 disabled:cursor-not-allowed disabled:bg-emerald-200 disabled:text-emerald-700',
    sensorUnavailableButton: 'rounded-lg bg-slate-600 px-3 py-2 text-sm font-extrabold text-white transition hover:bg-slate-700 disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-500',
    sensorConfirmOverlay: 'fixed inset-0 z-[6100] flex items-center justify-center bg-slate-950/70 p-4',
    sensorConfirmCard: 'w-full max-w-md rounded-2xl border border-amber-200 bg-white p-5 shadow-2xl',
    sensorConfirmTitle: 'text-lg font-black text-[#19374f]',
    sensorConfirmText: 'mt-2 text-sm leading-relaxed text-slate-600',
    sensorConfirmError: 'mt-3 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm font-semibold text-red-700',
    sensorConfirmActions: 'mt-5 grid grid-cols-2 gap-3',
    sensorConfirmButton: 'rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-extrabold text-white hover:bg-emerald-700 disabled:cursor-wait disabled:opacity-60',
    sensorNoButton: 'rounded-lg bg-red-600 px-4 py-2.5 text-sm font-extrabold text-white hover:bg-red-700 disabled:opacity-60',
    root: 'flex min-h-0 flex-col gap-3 rounded-xl bg-[#eaf3fb] p-3 sm:p-4 lg:h-[calc(var(--admin-viewport-height)-9.2rem)]',
    statsGrid: 'grid grid-cols-2 gap-3 xl:grid-cols-4',
    statCardBase: 'cursor-default rounded-xl border border-slate-200 bg-white px-4 py-3 shadow-sm',
    statReports: 'text-rose-600',
    statPending: 'text-sky-600',
    statInProgress: 'text-amber-600',
    statResolved: 'text-emerald-600',
    statLabel: 'text-[0.65rem] font-bold uppercase tracking-wide text-slate-500',
    statValue: 'mt-1 text-2xl font-black leading-none',
    rainRankCard: 'relative min-h-0 rounded-xl border border-slate-200 bg-white p-3 shadow-sm',
    rainRankPopover: 'absolute left-0 right-0 top-[calc(100%+0.5rem)] z-50 max-h-[50dvh] overflow-auto rounded-xl border border-slate-200 bg-white p-3 shadow-2xl',
    rainRankHead: 'flex flex-wrap items-center justify-between gap-2 border-b border-slate-300 pb-2',
    rainRankTitle: 'text-base font-bold text-[#19374f]',
    rainRankUpdated: 'text-xs text-slate-500',
    rainRankEmpty: 'pt-2 text-sm text-slate-500',
    rainRankList: 'grid gap-2 pt-2 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5',
    rainRankSideList: 'mt-2 min-h-0 flex-1 space-y-2 overflow-y-auto pr-1',
    rainRankRow: 'rounded-lg border border-slate-200 bg-slate-50 p-2',
    rainRankName: 'text-sm font-extrabold text-[#12314b]',
    rainRankMeta: 'text-xs font-semibold text-slate-700',
    rainRankImpact: 'pt-1 text-xs text-rose-700',
    mainGrid: 'grid min-h-[20rem] gap-3 lg:grid-cols-[minmax(0,1fr)_320px] lg:flex-[1.35]',
    mapSideColumn: 'flex min-h-0 flex-col gap-2',
    mapCard: 'relative min-h-[20rem] overflow-hidden rounded-xl border border-slate-200 bg-[#1c3f5a] shadow-sm lg:min-h-0 lg:h-full',
    mapFrame: 'h-full w-full border-0',
    selectedCard: 'min-h-0 flex-1 overflow-auto rounded-xl border border-slate-200 bg-white p-3 text-sm text-[#233f53] shadow-sm',
    selectedTitle: 'mb-2 border-b border-slate-300 pb-1 text-base font-bold text-[#19374f]',
    selectedCode: 'font-bold',
    selectedRouteHeader: 'mt-2 border-t border-slate-300 pt-2 font-semibold',
    selectedEmpty: 'text-slate-500',
    lowerGrid: 'grid min-h-[15rem] min-w-0 gap-3 xl:grid-cols-[minmax(0,1fr)_minmax(320px,0.9fr)] lg:flex-[1.15]',
    floodIndicatorsCard: 'relative flex flex-col gap-3 overflow-hidden rounded-md border border-slate-400 bg-[#1c3f5a] p-3 sm:p-4 xl:h-[25rem] xl:min-h-[25rem] xl:flex-[0_0_25rem]',
    floodIndicatorsHead: 'flex flex-wrap items-center justify-between gap-2',
    floodIndicatorsTitle: 'm-0 text-base font-extrabold text-white',
    floodSensorGrid: 'grid flex-1 grid-cols-2 items-start gap-3 sm:grid-cols-3 xl:grid-cols-6',
    floodSensorCard: 'flex min-w-0 flex-col items-center gap-2',
    floodSensorName: 'min-h-[1.3rem] w-full truncate text-center text-sm font-black text-white sm:text-base',
    floodSensorGauge: 'water-gauge relative flex h-36 w-full max-w-[110px] items-end rounded-2xl border-2 border-slate-900 p-1 sm:h-44 xl:h-[220px]',
    incidentReportsTable: 'data-table min-w-[1100px] table-fixed',
    floodReportsTable: 'data-table min-w-[900px] table-fixed',
    incidentsCard: 'flex min-h-0 min-w-0 max-w-full flex-col overflow-hidden rounded-xl border border-slate-200 bg-white p-3 shadow-sm',
    incidentsHead: 'flex flex-wrap items-center justify-between gap-2 border-b border-slate-300 pb-2',
    incidentsTitle: 'text-base font-bold text-[#19374f]',
    filterWrap: 'flex flex-wrap gap-1',
    filterBase: 'rounded-full px-2.5 py-1 text-xs font-semibold',
    filterActive: 'bg-[#1f4e79] text-white',
    filterIdle: 'bg-slate-100 text-slate-600 hover:bg-slate-200',
    incidentsTableWrap: 'active-list-scroll mt-2 min-h-0 w-full min-w-0 max-w-full flex-1 overflow-x-auto overflow-y-auto overscroll-x-contain rounded-md border border-slate-300 bg-white pb-1',
    rowBase: 'cursor-pointer text-[#233f53]',
    rowSelected: '!bg-blue-50',
    rowLocation: 'truncate',
    statusChip: 'status-chip bg-slate-200 text-slate-700',
    floodLevelModerate: '!border !border-amber-300 !bg-amber-100 !text-amber-800',
    floodLevelHigh: '!border !border-red-300 !bg-red-100 !text-red-700',
    floodStatusActive: '!border !border-emerald-300 !bg-emerald-100 !text-emerald-800',
    floodStatusUnavailable: '!border !border-slate-300 !bg-slate-200 !text-slate-700',
    muted: 'text-slate-400',
    validationCard: 'flex min-h-0 min-w-0 max-w-full flex-col overflow-hidden rounded-xl border border-slate-200 bg-white p-3 text-sm shadow-sm',
    validationTitle: 'border-b border-slate-400 pb-1 text-base font-bold text-[#19374f]',
    validationScrollWrap: 'active-list-scroll mt-2 min-h-0 w-full min-w-0 max-w-full flex-1 overflow-x-hidden overflow-y-auto rounded-lg border border-slate-200 bg-slate-50 p-3',
    validationEmpty: 'text-slate-500',
    validationStack: 'w-full min-w-0 space-y-2',
    validationCurrent: 'font-semibold',
    actionRow: 'flex flex-wrap gap-2',
    actionBox: 'space-y-2 rounded border border-slate-300 bg-white p-2',
    assignNote: 'rounded border border-emerald-300 bg-emerald-50 px-2 py-2 text-[11px] text-emerald-800',
    actionSoloBox: 'rounded border border-slate-300 bg-white p-2',
  },

  postUpdates: {
    root: 'flex h-[calc(100dvh-8.7rem)] min-h-0 flex-col rounded-xl bg-[#eaf3fb] p-3 sm:p-4 lg:h-[calc(var(--admin-viewport-height)-9.2rem)]',
    grid: 'grid min-h-0 flex-1 gap-3 xl:grid-cols-[1.15fr_0.85fr]',
    composeCard: 'min-h-0 overflow-auto rounded-xl border border-slate-200 bg-white p-4 shadow-sm',
    cardTitle: 'text-lg font-black text-[#173750]',
    cardSub: 'mb-3 text-sm text-slate-500',
    twoCol: 'mt-2 grid grid-cols-2 gap-2',
    submitRow: 'mt-2 flex justify-end',
    feedCard: 'min-h-0 overflow-auto rounded-xl border border-slate-200 bg-white p-4 shadow-sm',
    feedTitle: 'mb-3 border-b border-slate-200 pb-2 text-lg font-black text-[#173750]',
    feedList: 'space-y-3',
    feedItem: 'rounded-lg border border-slate-200 bg-slate-50 p-3',
    feedHeader: 'flex items-center justify-between gap-2',
    feedHeadline: 'text-sm font-bold text-[#12314b]',
    feedMeta: 'text-xs text-slate-500',
    feedBody: 'mt-1 text-sm text-slate-700',
    feedBadgeRow: 'mb-1 flex flex-wrap gap-1',
    feedBadge: 'rounded-full bg-[#dbeafe] px-2 py-0.5 text-[11px] font-semibold text-[#1e3a8a]',
  },

};
