export const d = {
  btn: {
    primary: 'btn-primary',
    secondary: 'btn-secondary',
    danger: 'btn-danger',
    primaryMt2: 'btn-primary mt-2',
    dangerMt2: 'btn-danger mt-2',
    secondaryXs: 'btn-secondary px-2 py-1 text-xs',
    dangerXs: 'btn-danger px-2 py-1 text-xs',
    emerald: 'btn-primary bg-emerald-600 hover:bg-emerald-700',
    emeraldSm: 'h-9 rounded-md bg-emerald-600 px-4 text-sm font-bold text-white hover:bg-emerald-700 disabled:opacity-60',
    redSm: 'h-9 rounded-md bg-red-600 px-4 text-sm font-bold text-white hover:bg-red-700 disabled:opacity-60',
    accept: 'rounded bg-emerald-600 px-3 py-2 font-semibold text-white',
    decline: 'rounded bg-rose-600 px-3 py-2 font-semibold text-white',
    inProgress: 'rounded bg-sky-600 px-3 py-2 font-semibold text-white',
    resolved: 'rounded bg-violet-600 px-3 py-2 font-semibold text-white',
    acceptDisabled: 'rounded bg-emerald-600 px-3 py-2 font-semibold text-white disabled:opacity-60',
    declineDisabled: 'rounded bg-rose-600 px-3 py-2 font-semibold text-white disabled:opacity-60',
    inProgressDisabled: 'rounded bg-sky-600 px-3 py-2 font-semibold text-white disabled:opacity-60',
    resolvedDisabled: 'rounded bg-violet-600 px-3 py-2 font-semibold text-white disabled:opacity-60',
    neutral: 'btn-secondary',
    warning: 'rounded bg-[#1f4e79] px-4 py-2 font-semibold text-white hover:bg-[#173a5b] disabled:opacity-60',
  },

  modal: {
    overlay: 'fixed inset-0 z-40 flex items-center justify-center bg-slate-900/70 p-4',
    card: 'w-full max-w-2xl rounded-lg bg-white p-3 shadow-xl',
    header: 'mb-2 flex items-center justify-between',
    title: 'text-sm font-bold text-slate-700',
    close: 'rounded border border-slate-300 px-2 py-1 text-xs font-semibold text-slate-600',
    image: 'max-h-[82dvh] w-full rounded border border-slate-200 object-contain',
  },

  shell: {
    root: 'barangay-desktop-scale app-bg min-h-[var(--barangay-viewport-height)] w-full overflow-x-hidden text-slate-900',
    layout: 'flex min-h-[var(--barangay-viewport-height)] flex-col lg:grid lg:grid-cols-[228px_minmax(0,1fr)] xl:grid-cols-[240px_minmax(0,1fr)]',
    aside: 'hidden flex-col gap-4 border-r border-slate-700/60 bg-[#0b2e4e] px-4 py-4 lg:flex lg:min-h-[var(--barangay-viewport-height)]',
    mobileTop: 'sticky top-0 z-30 border-b border-slate-300 bg-white/95 px-3 py-2 pt-[max(0.5rem,env(safe-area-inset-top))] backdrop-blur lg:hidden',
    mobileTopInner: 'flex items-center justify-between gap-2',
    mobileLogoWrap: 'flex min-w-0 items-center gap-2',
    mobileLogoText: 'min-w-0',
    mobileJurisdiction: 'truncate text-[0.65rem] font-semibold text-slate-500',
    mobileLogo: 'h-9 w-9 rounded-full border border-[#f4b400] bg-white object-cover',
    mobileBrand: 'text-lg font-extrabold leading-none text-[#0b2e4e]',
    mobileLogout: 'rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-sm font-semibold text-slate-700',
    mobileNav: 'fixed bottom-0 left-0 right-0 z-40 grid grid-cols-5 border-t border-slate-300 bg-white/95 p-2 pb-[calc(env(safe-area-inset-bottom)+0.5rem)] backdrop-blur lg:hidden',
    mobileNavItem: 'truncate rounded-lg px-1.5 py-2 text-center text-[0.7rem] font-bold transition-colors sm:px-2 sm:text-xs',
    mobileNavActive: 'bg-[#1f4e79] text-white',
    mobileNavIdle: 'text-[#1f4e79] hover:bg-slate-100',
    logoWrap: 'flex items-center gap-2 rounded-2xl border border-slate-500/30 bg-[#163b60] px-3 py-2.5',
    logo: 'h-9 w-9 rounded-full border border-[#f4b400] bg-white object-cover',
    city: 'text-[0.74rem] uppercase tracking-[0.2em] text-slate-300',
    brand: 'text-[1.95rem] font-extrabold leading-none text-white lg:text-[2.08rem]',
    nav: 'grid grid-cols-2 gap-3 sm:grid-cols-4 lg:flex lg:flex-col lg:gap-4',
    navItem: 'flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-base font-semibold tracking-[0.01em] transition-colors lg:py-3.5 lg:text-[1.08rem]',
    navIcon: 'h-5 w-5 shrink-0',
    navItemActive: 'bg-[#2a5d8d] text-white shadow-sm',
    navItemIdle: 'text-slate-100 hover:bg-[#163b60]',
    accountsDropdownWrap: 'mt-2 space-y-2 rounded-xl border border-slate-500/35 bg-[#163b60] p-2',
    accountsDropdownItem: 'w-full rounded-lg px-3 py-2 text-left text-sm font-bold transition',
    accountsDropdownItemActive: 'border border-sky-300 bg-sky-700 text-white',
    accountsDropdownItemIdle: 'bg-[#2a5d8d] text-white hover:bg-[#346e9f]',
    monitoringDropdownWrap: 'mb-2 mt-3 space-y-3',
    monitoringDropdownPanel: 'space-y-2 rounded-xl border border-slate-500/35 bg-[#163b60] p-2',
    monitoringDropdownButton: 'w-full rounded-lg bg-[#2a5d8d] px-3 py-2 text-left text-sm font-bold text-white transition hover:bg-[#346e9f]',
    monitoringDropdownButtonActive: 'mt-2 w-full rounded-lg border border-sky-300 bg-sky-700 px-3 py-2 text-left text-sm font-bold text-white',
    monitoringDropdownRows: 'mt-2 max-h-[34vh] space-y-2 overflow-y-auto pr-1',
    monitoringDropdownItem: 'flex w-full items-center justify-between rounded-xxl bg-[#2a5d8d] px-3 py-3 text-left text-base font-semibold text-white shadow-sm',
    monitoringDropdownCheck: 'h-4 w-4 min-h-4 min-w-4 max-h-4 max-w-4 shrink-0 rounded-sm border border-slate-200 accent-sky-400',
    monitoringFloodLegendDetails: 'rounded-lg border border-slate-500/45 bg-[#0f2f4d] p-2 text-xs text-slate-100',
    monitoringFloodLegendSummary: 'cursor-pointer font-bold text-sky-100',
    monitoringFloodLegendBody: 'mt-2 max-h-28 space-y-1 overflow-y-auto pr-1 text-[11px] leading-relaxed text-slate-200',
    monitoringFloodLegendRow: 'flex items-center gap-2',
    monitoringFloodLegendSwatch: 'inline-block h-2.5 w-4 rounded-sm border border-slate-100/60',
    logout: 'mt-1 w-full rounded-xl border border-slate-500/40 bg-[#133858] px-3 py-3 text-base font-bold text-white transition hover:bg-[#1b476f] lg:mt-auto',
    mainBase: 'w-full min-w-0 px-3 py-3 pb-24 md:px-4 md:py-4 lg:pb-4 xl:px-5',
    mainNoScroll: 'xl:h-[var(--barangay-viewport-height)] xl:overflow-hidden',
    mainScroll: 'xl:max-h-[var(--barangay-viewport-height)] xl:overflow-y-auto',
    header: 'mb-2.5 rounded-2xl border border-slate-200 bg-white/90 px-4 py-3 shadow-sm backdrop-blur',
    headerInner: 'flex flex-col items-stretch justify-between gap-3 sm:flex-row sm:flex-wrap sm:items-center',
    h1: 'text-xl font-extrabold leading-tight text-[#0b2e4e] md:text-[1.7rem]',
    subtitle: 'mt-1 text-[0.95rem] text-slate-600',
    actions: 'flex w-full flex-wrap gap-2 sm:w-auto [&>button]:flex-1 sm:[&>button]:flex-none',
  },

  page: {
    panelFill: 'panel flex h-full flex-col p-2',
    panelFillMd: 'panel flex h-full flex-col p-3',
    stack: 'space-y-3',
    error: 'rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700',
    loading: 'text-sm text-slate-500',
    sectionGrid: 'grid gap-2',
  },

  card: {
    metric: 'metric-card bg-white text-sm',
    metricValue: 'text-2xl font-extrabold',
    metricLabel: 'font-semibold text-slate-600',
  },

  form: {
    input: 'h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm',
    inputSm: 'h-9 rounded border border-slate-300 px-2 text-sm',
    inputSmDisabled: 'h-9 rounded border border-slate-200 bg-slate-100 px-2 text-sm text-slate-600',
    selectSm: 'w-full rounded border border-slate-300 px-2 py-1',
    textareaSm: 'w-full rounded border border-slate-300 px-2 py-1',
    textarea: 'mt-2 h-16 w-full rounded-lg border border-slate-300 bg-white p-2 text-sm',
    select: 'h-10 rounded-lg border border-slate-300 px-2 text-sm',
  },

  table: {
    main: 'data-table',
    wrap: 'active-list-scroll flex-1 overflow-auto rounded-md border border-slate-300 bg-white',
    empty: 'px-2 py-8 text-center text-sm text-slate-500',
  },

  login: {
    root: 'barangay-desktop-scale app-bg min-h-[var(--barangay-viewport-height)] w-full',
    layout: 'grid min-h-[var(--barangay-viewport-height)] w-full bg-white lg:grid-cols-[1.02fr_0.98fr]',
    left: 'order-2 flex flex-col justify-center bg-[linear-gradient(155deg,#f8fbff_0%,#edf3fb_60%,#e4edf8_100%)] px-5 py-8 sm:px-10 md:px-14 lg:order-1 lg:px-16',
    overline: 'mb-5 text-xs font-semibold uppercase tracking-[0.28em] text-slate-500 sm:mb-7',
    title: "mb-2 text-[clamp(2rem,5vw,3rem)] font-black tracking-tight text-[#0b2e4e] [font-family:'Sora',sans-serif]",
    subtitle: 'mb-6 max-w-xl text-sm text-slate-600 sm:mb-8',
    form: 'w-full max-w-[min(560px,100%)] space-y-4 sm:space-y-5',
    input: 'h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-sm text-slate-700 shadow-[0_2px_6px_rgba(15,41,72,0.12)] outline-none transition focus:border-[#1f4e79]',
    rememberLabel: 'flex cursor-pointer items-center gap-2 text-sm font-medium text-[#1f3c54]',
    checkbox: 'h-4 w-4 rounded border-slate-400 text-[#12314b]',
    error: 'text-sm font-medium text-red-600',
    loginBtn: 'h-12 w-full rounded-xl bg-[#1f4e79] text-base font-bold text-white shadow-[0_4px_10px_rgba(18,49,75,0.25)] transition hover:bg-[#173a5b] disabled:cursor-not-allowed disabled:opacity-60',
    right: 'relative order-1 flex min-h-[220px] items-center justify-center overflow-hidden bg-[#0f3558] sm:min-h-[280px] lg:order-2 lg:min-h-[var(--barangay-viewport-height)]',
    heroImg: 'absolute inset-0 h-full w-full object-cover opacity-20',
    overlay: 'absolute inset-0 bg-gradient-to-b from-[#1f5f93]/45 to-[#0b2740]/75',
    heroBody: 'relative z-10 flex max-w-sm flex-col items-center px-4 text-center text-white',
    seal: 'mb-4 h-24 w-24 rounded-full border-[5px] border-[#f6d84c] bg-white object-cover shadow-xl sm:h-28 sm:w-28 lg:mb-5 lg:h-36 lg:w-36 lg:border-[6px]',
    heroTitle: "text-[clamp(1rem,3.8vw,2rem)] font-black leading-tight [font-family:'Sora',sans-serif]",
  },

  dashboard: {
    root: 'flex min-h-0 flex-col gap-2 lg:h-[calc(var(--barangay-viewport-height)-9.2rem)]',
    topActions: 'btn-secondary',
    topPrimary: 'btn-primary',
    metricsGrid: 'grid gap-2 sm:grid-cols-2 xl:grid-cols-4',
    metricGradient: 'metric-card bg-gradient-to-r py-2 text-white',
    cardEmergency: 'from-[#f25358] to-[#ef8b8f]',
    cardTeams: 'from-[#2ca3d8] to-[#67c8db]',
    cardEvac: 'from-[#efad09] to-[#efd24c]',
    cardEvacuees: 'from-[#2bb39e] to-[#72d5a2]',
    metricValue: 'text-[1.55rem] font-black leading-none',
    metricLabel: 'mt-1 text-[0.95rem] font-extrabold',
    overviewGrid: 'grid min-h-0 flex-1 gap-2 2xl:grid-cols-[1.1fr_1fr]',
    reportsPanel: 'panel flex min-h-0 flex-col p-2',
    reportsTitle: 'px-2 text-[1.1rem] font-black leading-tight text-[#0b2e4e]',
    reportsContentGrid: 'mt-2 min-h-0 flex-1 overflow-auto',
    reportsWrap: 'mt-2 min-h-0 flex-1 overflow-auto',
    insightsRow: 'grid gap-2 lg:grid-cols-[1.2fr_1fr]',
    reportsTable: 'data-table min-w-[560px] text-xs sm:min-w-[720px] sm:text-sm',
    reportsPriorityBlock: 'min-h-0 rounded-lg border border-slate-200 bg-slate-50 p-2',
    reportsPriorityTitle: 'text-sm font-black text-[#143650]',
    reportsPriorityGrid: 'mt-2 grid gap-2 sm:grid-cols-3',
    priorityCardHigh: 'rounded-md border border-rose-200 bg-rose-50 p-2',
    priorityCardMedium: 'rounded-md border border-amber-200 bg-amber-50 p-2',
    priorityCardLow: 'rounded-md border border-emerald-200 bg-emerald-50 p-2',
    priorityCardTitle: 'text-xs font-extrabold uppercase tracking-wide text-[#17354c]',
    priorityList: 'mt-1 max-h-28 space-y-1 overflow-y-auto',
    priorityItem: 'text-xs font-semibold text-slate-700',
    priorityButton: 'block w-full rounded px-1 py-0.5 text-left text-xs font-semibold text-slate-700 hover:bg-white',
    priorityButtonActive: 'bg-white ring-1 ring-[#1f4e79]',
    priorityEmpty: 'text-xs text-slate-500',
    thHiddenMd: 'hidden md:table-cell',
    tdStrong: 'font-semibold text-slate-800',
    tdTruncate: 'truncate',
    statusChip: 'status-chip bg-slate-200 text-slate-700',
    muted: 'text-slate-400',
    statusMapPanel: 'panel grid min-h-0 gap-2 p-2 lg:grid-cols-[1fr_1fr]',
    statusColumn: 'grid min-h-0 gap-2 lg:grid-rows-[minmax(0,2fr)_minmax(0,1fr)_minmax(0,1fr)]',
    statusCard: 'flex min-h-0 flex-col rounded-xl border border-slate-200 bg-white',
    statusTitle: 'border-b border-slate-200 px-3 py-2 text-[1rem] font-black leading-tight',
    statusList: 'min-h-[12rem] max-h-[16rem] flex-1 space-y-2 overflow-y-auto px-3 py-2 lg:min-h-0 lg:max-h-none',
    areaCardBase: 'rounded-lg border p-2',
    areaCardActive: 'border-emerald-300 bg-emerald-50/50',
    areaCardIdle: 'border-slate-200 bg-slate-50',
    areaName: 'text-sm font-extrabold text-[#12314b]',
    areaBarangay: 'text-xs text-slate-500',
    areaMeta: 'mt-1 flex items-center justify-between text-xs',
    areaOcc: 'font-semibold text-amber-600',
    areaCap: 'text-slate-600',
    mapWrap: 'min-h-[18rem] overflow-hidden rounded-xl border border-slate-200 bg-white sm:min-h-[22rem] lg:min-h-0',
    mapFrame: 'h-full w-full border-0',
    rainRankCard: 'relative min-h-0 rounded-xl border border-sky-200 bg-sky-50 p-3',
    rainRankPopover: 'absolute left-0 right-0 top-[calc(100%+0.5rem)] z-50 max-h-[50dvh] overflow-auto rounded-xl border border-sky-200 bg-sky-50 p-3 shadow-2xl',
    rainRankHead: 'flex items-start justify-between gap-2 border-b border-sky-200 pb-2',
    rainRankTitle: 'text-sm font-black text-sky-900',
    rainRankUpdated: 'text-xs text-slate-500',
    rainRankEmpty: 'pt-2 text-sm text-slate-600',
    rainRankList: 'mt-2 grid gap-2 sm:grid-cols-2',
    rainRankRow: 'rounded-md border border-sky-200 bg-white p-2',
    rainRankName: 'text-xs font-extrabold text-[#12314b]',
    rainRankMeta: 'text-xs font-semibold text-slate-700',
    smartAlertCard: 'min-h-[9rem] rounded-xl border border-rose-200 bg-rose-50 p-3',
    smartAlertTitle: 'text-sm font-black text-rose-800',
    smartAlertList: 'mt-2 max-h-36 space-y-2 overflow-y-auto',
    smartAlertItem: 'rounded-md border border-rose-200 bg-white px-2 py-1.5 text-xs font-semibold text-rose-800',
    smartAlertEmpty: 'text-xs text-rose-700/80',
    composeGrid: 'grid gap-2 xl:grid-cols-2',
    composePanel: 'panel p-3',
    composeTitle: 'text-[1rem] font-black',
    selectGrid: 'mt-2 grid grid-cols-2 gap-2',
  },

  admin: {
    actionAdd: 'btn-primary',
    root: 'panel flex h-[calc(100dvh-8.7rem)] min-h-0 flex-col p-3 lg:h-[calc(var(--barangay-viewport-height)-9.2rem)]',
    headerRow: 'mb-2 flex flex-wrap items-center justify-between gap-2',
    title: 'text-lg font-black text-[#1a3650] sm:text-xl',
    searchRow: 'flex flex-wrap items-center gap-2',
    search: 'h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm sm:w-80',
    archiveButton: 'inline-flex h-10 items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 text-sm font-semibold text-[#1a3650] hover:bg-slate-50',
    archiveIcon: 'h-4 w-4 object-contain',
    form: 'mb-2 grid gap-2 rounded-md border border-slate-300 bg-[#f7f8f9] p-2 sm:grid-cols-2 xl:grid-cols-4',
    idBox: 'rounded border border-slate-300 bg-white px-2 py-2 text-sm font-semibold text-slate-700',
    formActions: 'flex flex-wrap gap-2 sm:col-span-2 xl:col-span-4',
    tableHead: 'sticky top-0',
    thHiddenMd: 'hidden md:table-cell',
    thHiddenLg: 'hidden lg:table-cell',
    thHiddenXl: 'hidden xl:table-cell',
    row: 'text-[#2b465b]',
    truncate: 'truncate',
    tdHiddenTruncateMd: 'hidden truncate md:table-cell',
    tdHiddenLg: 'hidden lg:table-cell',
    tdHiddenTruncateXl: 'hidden truncate xl:table-cell',
    actions: 'flex gap-1',
    archiveModalCard: 'w-full max-w-3xl rounded-lg bg-white p-3 shadow-xl',
    archiveModalBody: 'max-h-[75dvh] overflow-auto pr-1',
    archiveList: 'space-y-2',
    archiveItem: 'flex flex-wrap items-start justify-between gap-2 rounded-lg border border-slate-200 bg-slate-50 p-2',
    archiveName: 'text-sm font-bold text-[#1a3650]',
    archiveMeta: 'text-xs text-slate-600',
    archiveActions: 'flex w-full flex-col gap-2 sm:w-auto sm:flex-row sm:justify-end',
    archiveActionButton: 'w-full sm:w-auto whitespace-nowrap',
    archiveEmpty: 'text-sm text-slate-500',
  },

  evac: {
    actionAdd: 'btn-primary bg-emerald-600 hover:bg-emerald-700',
    root: 'panel flex h-[calc(100dvh-8.7rem)] min-h-0 flex-col p-2 lg:h-[calc(var(--barangay-viewport-height)-9.2rem)]',
    grid: 'grid min-h-0 flex-1 gap-2 2xl:grid-cols-[1.3fr_1fr] 2xl:overflow-hidden',
    mapSection: 'panel flex min-h-0 flex-col p-2',
    mapTitle: 'text-[1rem] font-black leading-tight',
    mapWrap: 'mt-2 min-h-0 flex-1 overflow-hidden rounded border border-slate-300 bg-white',
    mapFrame: 'h-full w-full border-0',
    detailSection: 'panel flex min-h-0 flex-col overflow-hidden',
    detailTitle: 'border-b border-slate-300 px-3 py-2 text-[1rem] font-black',
    detailBody: 'px-3 py-2',
    detailLabel: 'mb-2 text-xs font-bold text-slate-600',
    formStack: 'space-y-1.5',
    twoCol: 'grid gap-2 sm:grid-cols-2',
    threeCol: 'grid gap-2 sm:grid-cols-3',
    formActions: 'mt-2 grid gap-2 sm:grid-cols-[1fr_auto]',
    formActionsWide: 'mt-2 grid gap-2 sm:grid-cols-3',
    editOnlyActions: 'mt-3 flex w-full justify-end',
    otherWrap: 'min-h-0 flex-1 border-t border-slate-300 px-3 py-2',
    otherTitle: 'mb-2 text-[0.95rem] font-black',
    otherList: 'h-full min-h-0 space-y-2 overflow-y-auto pr-1',
    otherItem: 'w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-left hover:bg-slate-100',
    otherName: 'text-sm font-black text-[#12314b]',
    otherBarangay: 'text-xs text-slate-500',
    otherDistance: 'text-sm font-bold text-teal-600',
  },

  monitoring: {
    actionEvac: 'btn-secondary',
    root: 'flex min-h-0 flex-col gap-2 xl:h-[calc(var(--barangay-viewport-height)-9.2rem)]',
    statsGrid: 'grid grid-cols-2 gap-3 xl:grid-cols-4',
    statCardBase: 'cursor-default rounded-xl border border-slate-200 bg-white px-4 py-3 shadow-sm',
    statReports: 'text-rose-600',
    statPending: 'text-sky-600',
    statInProgress: 'text-amber-600',
    statResolved: 'text-emerald-600',
    statLabel: 'text-[0.65rem] font-bold uppercase tracking-wide text-slate-500',
    statValue: 'mt-1 text-2xl font-black leading-none',
    rainRankCard: 'panel relative p-2',
    rainRankPopover: 'absolute left-0 right-0 top-[calc(100%+0.5rem)] z-50 max-h-[50dvh] overflow-auto rounded-xl border border-slate-200 bg-white p-3 shadow-2xl',
    rainRankHead: 'flex flex-wrap items-center justify-between gap-2 border-b border-slate-300 pb-2',
    rainRankTitle: 'text-base font-bold text-[#19374f]',
    rainRankUpdated: 'text-xs text-slate-500',
    rainRankEmpty: 'pt-2 text-sm text-slate-500',
    rainRankList: 'grid gap-2 pt-2 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5',
    rainRankSideList: 'grid min-w-[28rem] gap-2 pt-2',
    rainRankRow: 'rounded-lg border border-slate-200 bg-slate-50 p-2',
    rainRankName: 'text-sm font-extrabold text-[#12314b]',
    rainRankMeta: 'text-xs font-semibold text-slate-700',
    rainRankImpact: 'pt-1 text-xs text-rose-700',
    mainGrid: 'grid min-h-[20rem] gap-2 xl:grid-cols-[minmax(0,1fr)_320px] xl:flex-[1.35]',
    mapSideColumn: 'flex min-h-0 flex-col gap-2',
    mapCard: 'relative min-h-[20rem] overflow-hidden rounded-md border border-slate-400 bg-[#1c3f5a] xl:min-h-0 xl:h-full',
    mapFrame: 'h-full w-full border-0',
    selectedCard: 'panel min-h-0 flex-1 overflow-auto p-3 text-sm text-[#233f53]',
    selectedTitle: 'mb-3 border-b border-slate-300 pb-2 text-lg font-bold text-[#19374f]',
    incidentDetailGrid: 'incident-detail-grid',
    incidentDetailColumn: 'incident-detail-column',
    incidentDetailMetaColumn: 'incident-detail-column incident-detail-meta-column',
    incidentDetailWide: 'incident-detail-wide',
    selectedCode: 'font-bold',
    selectedRouteHeader: 'mt-2 border-t border-slate-300 pt-2 font-semibold',
    selectedEmpty: 'text-slate-500',
    lowerGrid: 'grid min-h-[17rem] min-w-0 gap-2 xl:grid-cols-[minmax(0,1fr)_minmax(400px,1.1fr)] xl:flex-[1.15]',
    floodIndicatorsCard: 'relative flex flex-col gap-3 overflow-hidden rounded-md border border-slate-400 bg-[#1c3f5a] p-3 sm:p-4 xl:h-[25rem] xl:min-h-[25rem] xl:flex-[0_0_25rem]',
    floodIndicatorsHead: 'flex flex-wrap items-center justify-between gap-2',
    floodIndicatorsTitle: 'm-0 text-base font-extrabold text-white',
    floodSensorGrid: 'grid flex-1 grid-cols-2 items-start gap-3 sm:grid-cols-3 xl:grid-cols-6',
    floodSensorCard: 'flex min-w-0 flex-col items-center gap-2',
    floodSensorName: 'min-h-[1.3rem] w-full truncate text-center text-sm font-black text-white sm:text-base',
    floodSensorGauge: 'water-gauge relative flex h-36 w-full max-w-[110px] items-end rounded-2xl border-2 border-slate-900 p-1 sm:h-44 xl:h-[220px]',
    incidentReportsTable: 'data-table min-w-[760px] table-fixed',
    floodReportsTable: 'data-table min-w-[900px] table-fixed',
    incidentsCard: 'panel flex min-h-0 min-w-0 max-w-full flex-col overflow-hidden p-2',
    incidentsHead: 'flex flex-wrap items-center justify-between gap-2 border-b border-slate-300 pb-2',
    incidentsTitle: 'text-base font-bold text-[#19374f]',
    filterWrap: 'flex flex-wrap gap-1',
    filterBase: 'rounded-full px-2.5 py-1 text-xs font-semibold',
    filterActive: 'bg-[#1f4e79] text-white',
    filterIdle: 'bg-slate-100 text-slate-600 hover:bg-slate-200',
    incidentsTableWrap:
      'active-list-scroll mt-2 min-h-0 w-full min-w-0 max-w-full flex-1 overflow-x-scroll overflow-y-auto overscroll-x-contain rounded-md border border-slate-300 bg-white pb-1',
    rowBase: 'cursor-pointer text-[#233f53]',
    rowSelected: '!bg-blue-50',
    rowLocation: 'truncate',
    statusChip: 'status-chip bg-slate-200 text-slate-700',
    floodLevelModerate: '!border !border-amber-300 !bg-amber-100 !text-amber-800',
    floodLevelHigh: '!border !border-red-300 !bg-red-100 !text-red-700',
    floodStatusActive: '!border !border-emerald-300 !bg-emerald-100 !text-emerald-800',
    floodStatusUnavailable: '!border !border-slate-300 !bg-slate-200 !text-slate-700',
    muted: 'text-slate-400',
    validationCard:
      'panel flex min-h-0 min-w-0 max-w-full flex-col overflow-hidden p-3 text-sm',
    validationTitle: 'border-b border-slate-400 pb-1 text-base font-bold text-[#19374f]',
    validationScrollWrap:
      'active-list-scroll mt-2 min-h-0 w-full min-w-0 max-w-full flex-1 overflow-x-hidden overflow-y-auto rounded-md border border-slate-300 bg-white p-2',
    validationEmpty: 'text-slate-500',
    validationStack: 'w-full min-w-0 space-y-2',
    validationCurrent: 'font-semibold',
    actionRow: 'flex flex-wrap gap-2',
    actionBox: 'space-y-2 rounded border border-slate-300 bg-white p-2',
    actionSoloBox: 'rounded border border-slate-300 bg-white p-2',
    assignNote: 'rounded border border-emerald-300 bg-emerald-50 px-3 py-3 text-base font-medium leading-6 text-emerald-800',
  },

  postUpdates: {
    root: 'flex h-[calc(100dvh-8.7rem)] min-h-0 flex-col gap-2 lg:h-[calc(var(--barangay-viewport-height)-9.2rem)]',
    grid: 'grid min-h-0 flex-1 gap-2 xl:grid-cols-[1.15fr_0.85fr]',
    composeCard: 'panel min-h-0 overflow-auto p-3',
    cardTitle: 'text-[1rem] font-black text-[#19374f]',
    cardSub: 'mb-2 text-xs text-slate-500',
    twoCol: 'mt-2 grid grid-cols-2 gap-2',
    submitRow: 'mt-2 flex justify-end',
    feedCard: 'panel min-h-0 overflow-auto p-3',
    feedTitle: 'mb-2 border-b border-slate-300 pb-1 text-base font-bold text-[#19374f]',
    feedList: 'space-y-2',
    feedItem: 'rounded-lg border border-slate-200 bg-white p-2',
    feedHeader: 'flex items-center justify-between gap-2',
    feedHeadline: 'text-sm font-bold text-[#12314b]',
    feedMeta: 'text-xs text-slate-500',
    feedBody: 'mt-1 text-sm text-slate-700',
    feedBadgeRow: 'mb-1 flex flex-wrap gap-1',
    feedBadge: 'rounded-full bg-[#dbeafe] px-2 py-0.5 text-[11px] font-semibold text-[#1e3a8a]',
  },

};
